.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-LAST" "1" "June 2015" "" ""
.
.SH "NAME"
\fBgit\-last\fR \- Display last x number of commits
.
.SH "SYNOPSIS"
\fBgit\-last\fR <NUMBER>
.
.SH "DESCRIPTION"
Displays last \fBX\fR number of commits\. If no number is provided, return the last commit only\.
.
.SH "OPTIONS"
<NUMBER>
.
.SH "EXAMPLES"
.
.nf

$ git last 4
.
.fi
.
.SH "AUTHOR"
Written by Courtney Ivey <\fIoxocodes@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/oxocode/git\-work/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/oxocode/git\-work\fR>
