.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-CREATE\-FEATURE" "1" "June 2015" "" ""
.
.SH "NAME"
\fBgit\-create\-feature\fR \- Create feature branch
.
.SH "SYNOPSIS"
\fBgit\-create\-feature\fR <branchname>
.
.SH "DESCRIPTION"
Creates local and remote feature branch named <branchname>\.
.
.SH "OPTIONS"
<branchname>
.
.P
The name of the feature branch to create\.
.
.SH "EXAMPLES"
.
.nf

$ git create\-feature integration
.
.fi
.
.SH "AUTHOR"
Written by Courtney Ivey <\oxocodes@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/oxocode/git\-work/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/oxocode/git\-work\fR>
