.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-WORK" "1" "June 2015" "" ""
.
.SH "NAME"
\fBgit\-work\fR \- Command Line Utilities for git work
.
.SH "SYNOPSIS"
\fBgit\-work\fR [\-v,\-\-version] [\-h,\-\-help] [update]
.
.SH "OPTIONS"
\-v, \-\-version
.
.P
Show git\-work version number\.
.
.P
\-h, \-\-help
.
.P
Show this help\. This option can also be used for any of the extras commands\.
.
.P
update
.
.P
Self update\.
.
.SH "COMMANDS"
.
.IP "\(bu" 4
\fBgit\-create\-feature(1)\fR Create feature branches
.
.IP "\(bu" 4
\fBgit\-archive\-feature(1)\fR Archive feature branches
.
.IP "\(bu" 4
\fBgit\-last(1)\fR Display last commit
.
.IP "" 0
.
.SH "AUTHOR"
Written by Courtney Ivey <\fIoxocodes@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/oxocode/git\-work/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/oxocode/git\-work\fR>
