#!/usr/bin/env bash
# git-work
#
# is-git-repo
# check to see if current dir/ is inside a git repo

is_git_repo() {
  git rev-parse --show-toplevel > /dev/null 2>&1
  result=$?
  if test $result != 0; then
    >&2 echo 'Not a git repo!'
    exit $result
  fi
}

is_git_repo
